# Reusable workflow for building and testing projects that use Stella
name: CI

on:
  workflow_call:

jobs:

  build:

    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Mac OS Big Sur
            os: macos-11
          - name: Ubuntu
            os: ubuntu-latest
#           - name: Windows Server
#             os: windows-latest

    steps:

      - uses: actions/checkout@v2

      - name: Clone Stella
        run: git submodule update --init --remote Stella

      - name: Cache Ninja
        id: cache-ninja
        uses: actions/cache@v2
        with:
          path: ./Stella/ninja
          key: ${{ runner.os }}-ninja

      - name: Clone Ninja
        if: steps.cache-ninja.outputs.cache-hit != 'true'
        run: cd Stella && git submodule update --init --remote ninja

      - name: Bootstrap Ninja
        if: steps.cache-ninja.outputs.cache-hit != 'true'
        run: cd Stella/ninja && python3 configure.py --bootstrap

      - name: Cache Googletest
        id: cache-gtest
        uses: actions/cache@v2
        with:
          path: ./Stella/googletest
          key: ${{ runner.os }}-gtest

      - name: Clone Googletest
        if: steps.cache-gtest.outputs.cache-hit != 'true'
        run: cd Stella && git submodule update --init --remote googletest

      - name: Bootstrap Googletest
        if: steps.cache-gtest.outputs.cache-hit != 'true'
        run: |
          cd Stella/googletest && \
          mkdir build && \
          cd build && \
          cmake .. && \
          make

      - name: Gather python packages required by Stella
        run: pip3 install -r Stella/requirements.txt

      - name: Run Stella to gather dependencies
        run: python3 ./Stella/stella.py

      - name: Run the ninja build
        run: ./Stella/ninja/ninja

      - name: Run the tests
        run: ./build/bin/run-tests || echo "Test binary missing"
